
steps:

  ### Add Tag
  
    - id: 'add-tag'
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            gcloud artifacts docker tags add ${_REGION}-docker.pkg.dev/${PROJECT_ID}/quickstart-docker-repo/$_APP_NAME:${SHORT_SHA} \
              ${_REGION}-docker.pkg.dev/${PROJECT_ID}/quickstart-docker-repo/$_APP_NAME:$TAG_NAME \
              --quiet
  
  
  
  ### Deploy
    - id: 'deploy'
      name: 'gcr.io/cloud-builders/gcloud'
      env:
        - 'KUBECONFIG=/kube/config'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
            PROJECT=$$(gcloud config get-value core/project)          
  
            gcloud container clusters get-credentials "${_CLUSTER}" \
              --project "$${PROJECT}" \
              --zone "${_ZONE}"   
           
  
            sed -i 's|gcr.io/$PROJECT_ID/$_APP_NAME:.*|${_REGION}-docker.pkg.dev/${PROJECT_ID}/quickstart-docker-repo/$_APP_NAME:$TAG_NAME|' ./k8s/deployments/prod/*.yaml
            
            kubectl apply --namespace production --recursive -f k8s/deployments/prod
            kubectl apply --namespace production --recursive -f k8s/services
